services:
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT="8080"
      - API_KEYS="test-1111,test-2222"
      - CURRENCY_SERVICE="currency-service:50051"
      - CONVERSION_SERVICE="conversion-service:50051"
      - HISTORY_SERVICE="history-service:50051"
  currency:
    container_name: currency
    build:
      dockerfile: Dockerfile
      context: ./currency
    ports:
      - "8080:8080"
    environment:
      - TEST="some"
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: currency
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: