services:
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - PORT="8080"
      - API_KEYS="test-1111,test-2222"
      - CURRENCY_SERVICE="currency-service:50051"
      - CONVERSION_SERVICE="conversion-service:50051"
      - HISTORY_SERVICE="history-service:50051"
